# Generated by Django 4.1.2 on 2022-12-02 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"is_student": True},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_instructor",
            field=models.BooleanField(default=False, verbose_name="Instructor"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_student",
            field=models.BooleanField(default=False, verbose_name="Student"),
        ),
    ]
