# Generated by Django 4.1.2 on 2023-01-09 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_student_student_alter_user_is_instructor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
