# name: Deploy to PythonAnywhere

# on:
#   push:
#     branches:
#       - master

# jobs:
#   deploy:
#     name: Deploy to PythonAnywhere
#     runs-on: ubuntu-latest

#     steps:
#       - name: Wait for tests to pass
#         uses: actions/github-script@v7
#         with:
#           script: |
#             const { owner, repo } = context.repo;
#             const branch = context.ref.replace('refs/heads/', '');
#             const runs = await github.rest.actions.listWorkflowRunsForRepo({
#               owner,
#               repo,
#               branch,
#               status: 'completed',
#               per_page: 10
#             });

#             const lastTestRun = runs.data.workflow_runs.find(run => run.name === 'Django CI - Run Tests');
#             if (!lastTestRun || lastTestRun.conclusion !== 'success') {
#               core.setFailed('Latest test workflow did not succeed. Deployment aborted.');
#             }

#       - name: Set up SSH
#         run: |
#           mkdir -p ~/.ssh
#           echo "${{ secrets.PA_SSH_KEY }}" > ~/.ssh/id_rsa
#           chmod 600 ~/.ssh/id_rsa
#           ssh-keyscan ssh.pythonanywhere.com >> ~/.ssh/known_hosts

#       - name: Deploy to PythonAnywhere
#         run: ssh mahmoudateff07@ssh.pythonanywhere.com "bash ~/deploy.sh"
