name: Deploy to PythonAnywhere

on:
  workflow_run:
    workflows: ["Django CI - Run Tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PA_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ssh.pythonanywhere.com >> ~/.ssh/known_hosts

      - name: Deploy to PythonAnywhere
        run: ssh mahmoudateff07@ssh.pythonanywhere.com "bash ~/deploy.sh"
