name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PA_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ssh.pythonanywhere.com >> ~/.ssh/known_hosts

      - name: Run deploy script on PythonAnywhere
        run: |
          ssh mahmoudateff07@ssh.pythonanywhere.com "bash ~/deploy.sh"
