name: Django CI - Run Tests

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Black formatter
        run: |
          black .
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add .
            git commit -m "Auto-format code with Black"
            git push
          fi

      - name: Set environment variables
        run: |
          echo "DEBUG=True" >> $GITHUB_ENV
          echo "SECRET_KEY=dummy" >> $GITHUB_ENV

      - name: Run migrations
        run: python manage.py migrate --noinput

      - name: Run tests
        run: python manage.py test --verbosity=2

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.organization=mahmoudatif
            -Dsonar.projectKey=MahmoudAtif_E-learning-management-system
            -Dsonar.python.version=3.10
            -Dsonar.python.coverage.reportPaths=coverage.xml

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PA_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ssh.pythonanywhere.com >> ~/.ssh/known_hosts

      - name: Deploy to PythonAnywhere
        run: |
          ssh mahmoudateff07@ssh.pythonanywhere.com << 'EOF'
            cd /home/mahmoudateff07/E-learning-management-system
            source venv/bin/activate
            git pull origin master
            pip install -r requirements.txt
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            touch /var/www/mahmoudateff07_pythonanywhere_com_wsgi.py
          EOF

  # New Job: GitHub CodeQL Security Analysis
  codeql:
    name: CodeQL Security Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          config-file: .github/codeql/config.yml

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
